#!perl
use strict;
use warnings;

use App::KV2JSON;
print App::KV2JSON->run(@ARGV);

__END__

=encoding utf-8

=head1 NAME

kv2json - command line utility for building json

=head1 SYNOPSIS

    % kv2json var=baz blah=blah
    {"blah":"blah","var":"baz"}

    # array
    % kv2json fruits[]=apple,orange
    {"fruits":["apple","orange"]}

    # complicated structure
    % kv2json alice[age]=18 alice[gender]=female
    {"alice":{"gender":"female","age":"18"}}

    # numerify the value
    % kv2json age#=18
    {"age":18}

=head1 DESCRIPTION

kv2json is command line utility for building json.

=head1 LICENSE

Copyright (C) Songmu.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 AUTHOR

Songmu E<lt>y.songmu@gmail.comE<gt>

=cut

